// Filter presets. Each preset defines default parameter values.
// Parameters not listed fall back to 0 (neutral).

export const DEFAULT_PARAMS = {
  exposure: 0,
  contrast: 0,
  highlights: 0,
  shadows: 0,
  warmth: 0,
  tint: 0,
  saturation: 0,
  vibrance: 0,
  sharpening: 0,
  vignette: 0,
  highlightHue: 45,
  highlightStrength: 0,
  shadowHue: 220,
  shadowStrength: 0,
}

export const PRESETS = [
  {
    id: 'none',
    name: 'None',
    params: { ...DEFAULT_PARAMS },
  },
  {
    id: 'gold',
    name: 'Gold',
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.1,
      contrast: 20,
      highlights: -15,
      shadows: 20,
      warmth: 45,
      tint: -5,
      saturation: 10,
      vibrance: 20,
      sharpening: 15,
      vignette: 25,
      highlightHue: 42,      // golden yellow
      highlightStrength: 55,
      shadowHue: 210,        // cool blue-teal
      shadowStrength: 30,
    },
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    params: {
      ...DEFAULT_PARAMS,
      exposure: -0.1,
      contrast: 35,
      highlights: -25,
      shadows: 10,
      warmth: 10,
      saturation: -15,
      vibrance: 10,
      sharpening: 10,
      vignette: 40,
      highlightHue: 50,
      highlightStrength: 20,
      shadowHue: 195,
      shadowStrength: 45,
    },
  },
  {
    id: 'fade',
    name: 'Fade',
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.2,
      contrast: -20,
      highlights: -10,
      shadows: 35,
      warmth: 15,
      saturation: -20,
      vibrance: 5,
      vignette: 15,
    },
  },
  {
    id: 'cool',
    name: 'Cool',
    params: {
      ...DEFAULT_PARAMS,
      warmth: -35,
      tint: 5,
      contrast: 15,
      highlights: -10,
      saturation: 5,
      vibrance: 15,
      sharpening: 10,
      vignette: 20,
      highlightHue: 200,
      highlightStrength: 30,
      shadowHue: 240,
      shadowStrength: 25,
    },
  },
  {
    id: 'punch',
    name: 'Punch',
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.05,
      contrast: 40,
      highlights: -20,
      shadows: 15,
      saturation: 25,
      vibrance: 30,
      sharpening: 25,
      vignette: 30,
    },
  },
]
