// Filter presets. Each preset defines default parameter values.
// Parameters not listed fall back to 0 (neutral).

export const DEFAULT_PARAMS = {
  exposure: 0,
  contrast: 0,
  highlights: 0,
  shadows: 0,
  warmth: 0,
  tint: 0,
  saturation: 0,
  vibrance: 0,
  sharpening: 0,
  vignette: 0,
  grain: 0,
  highlightHue: 45,
  highlightStrength: 0,
  shadowHue: 220,
  shadowStrength: 0,
  // Per-hue HSL (Hue shift in degrees, Sat/Lum in -100 to +100)
  redsHue: 0,    redsSat: 0,    redsLum: 0,
  orangesHue: 0, orangesSat: 0, orangesLum: 0,
  yellowsHue: 0, yellowsSat: 0, yellowsLum: 0,
  greensHue: 0,  greensSat: 0,  greensLum: 0,
  cyansHue: 0,   cyansSat: 0,   cyansLum: 0,
  bluesHue: 0,   bluesSat: 0,   bluesLum: 0,
}

export const PRESETS = [
  {
    id: 'none',
    name: 'None',
    params: { ...DEFAULT_PARAMS },
  },
  {
    id: 'film',
    name: 'Film',
    // Tuned to match the reference: lifted shadows, warm earth tones,
    // heavily desaturated blues/cyans, olive-shifted greens, visible grain.
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.1,
      contrast: 18,
      highlights: -18,
      shadows: 48,
      warmth: 55,
      tint: -4,
      saturation: -8,
      vibrance: 15,
      grain: 30,
      vignette: 28,
      highlightHue: 40,
      highlightStrength: 32,
      shadowHue: 38,
      shadowStrength: 18,
      // Blues: heavily desaturate the sky
      bluesSat: -68,
      bluesHue: 5,
      bluesLum: 5,
      // Cyans: also present in sky, pull back
      cyansSat: -32,
      cyansLum: 3,
      // Greens: shift toward olive
      greensHue: 14,
      greensSat: -12,
      // Yellows/oranges: boost warm earth tones
      yellowsSat: 12,
      orangesSat: 15,
    },
  },
  {
    id: 'gold',
    name: 'Gold',
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.1,
      contrast: 20,
      highlights: -15,
      shadows: 20,
      warmth: 45,
      tint: -5,
      saturation: 10,
      vibrance: 20,
      sharpening: 15,
      vignette: 25,
      highlightHue: 42,      // golden yellow
      highlightStrength: 55,
      shadowHue: 210,        // cool blue-teal
      shadowStrength: 30,
    },
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    params: {
      ...DEFAULT_PARAMS,
      exposure: -0.1,
      contrast: 35,
      highlights: -25,
      shadows: 10,
      warmth: 10,
      saturation: -15,
      vibrance: 10,
      sharpening: 10,
      vignette: 40,
      highlightHue: 50,
      highlightStrength: 20,
      shadowHue: 195,
      shadowStrength: 45,
    },
  },
  {
    id: 'fade',
    name: 'Fade',
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.2,
      contrast: -20,
      highlights: -10,
      shadows: 35,
      warmth: 15,
      saturation: -20,
      vibrance: 5,
      vignette: 15,
    },
  },
  {
    id: 'cool',
    name: 'Cool',
    params: {
      ...DEFAULT_PARAMS,
      warmth: -35,
      tint: 5,
      contrast: 15,
      highlights: -10,
      saturation: 5,
      vibrance: 15,
      sharpening: 10,
      vignette: 20,
      highlightHue: 200,
      highlightStrength: 30,
      shadowHue: 240,
      shadowStrength: 25,
    },
  },
  {
    id: 'punch',
    name: 'Punch',
    params: {
      ...DEFAULT_PARAMS,
      exposure: 0.05,
      contrast: 40,
      highlights: -20,
      shadows: 15,
      saturation: 25,
      vibrance: 30,
      sharpening: 25,
      vignette: 30,
    },
  },
]
